TeamProjectWeb/Controllers/MVC/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamProject.Business.Contracts;
using TeamProject.Business.Entities;
using TeamProjectWeb.Models;

namespace TeamProjectWeb.Controllers.MVC
{
    public class ContactsController : Controller
    {

        private IContactService _contactManager;

        public ContactsController(IContactService contactManager)
        {
            _contactManager = contactManager;
        }

        private ViewModelFactory _theModelFactory;
        protected ViewModelFactory TheModelFactory
        {
            get
            {
                if (_theModelFactory == null)
                {
                    _theModelFactory = new ViewModelFactory(_contactManager);
                }
                return _theModelFactory;
            }
        }

        // GET: Contacts
        public ActionResult Index()
        {

            IEnumerable<Contact> contacts= _contactManager.GetContacts();
            return View(contacts);
        }



        // GET: Contacts/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult AdminDetails()
        {
            int id = 1; //For now hardcoded but needs to be replaced by the user id logged in
            Contact contact = _contactManager.GetContact(id);
            ContactBasicViewModel contactBasicViewModel = TheModelFactory.Create(contact);
            return PartialView(contactBasicViewModel);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contacts/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TeamProjectWeb/Controllers/MVC/ProjectsController.cs
using TeamProjectWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamProject.Business.Contracts;
using TeamProject.Business.Entities;

namespace TeamProjectWeb.Controllers.MVC
{
    public class ProjectsController : BaseController
    {
        ITeamProjectService _teamProjectService; 
        IContactService _contactService;

        public ProjectsController(ITeamProjectService teamProjectService, IContactService contactService)
        {
            _teamProjectService = teamProjectService;
            _contactService = contactService;
        }

        // GET: Projects
        public ActionResult Index()
        {
            IEnumerable<Project> projects=  _teamProjectService.GetTeamProjects();
            IEnumerable<ProjectItemViewModel> projectItems = new ViewModelFactory().Create(projects);
            return View(projectItems);
        }

        // GET: Projects/Details/5
        public ActionResult Details(int id)
        {
          Project project=  _teamProjectService.GetTeamProject(id);
          ProjectViewModel projectViewModel = new ViewModelFactory(_contactService).Create(project);
          return View(projectViewModel);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Projects/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Projects/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TeamProjectWeb/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        <a href="" onclick="window.open('https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S','insipinia'); return false;" target="_blank">Template by Insipina</a>
</div>
    <div>
        <a href="" onclick="window.open('http://codingbyhectorflores.com/','insipinia'); return false;" target="_blank"><strong>Hector Flores</strong></a> Light Project Tracking &copy; 2014-2015
    </div>
</div>

TeamProjectWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Light Project Tracking</title>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
                                              
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

          
            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/metsiMenu")
    @Scripts.Render("~/plugins/pace")
    @Scripts.Render("~/bundles/inspinia")
    @RenderSection("scripts", required: false)
</body>
</html>

TeamProjectWeb/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
          
                @Html.Action("AdminDetails","Contacts")

                <div class="logo-element">
                    <i class="fa fa-pagelines"> LPT</i>
                </div>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Projects")"><i class="fa fa-pagelines"></i> <span class="nav-label">Home</span> </a>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Contacts")"><i class="fa fa-user"></i> <span class="nav-label">Team</span> </a>
            </li>
          
        </ul>
    </div>
</nav>

TeamProjectWeb/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">


        <div class="navbar-header" style="width:500px">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <h2><i class="fa fa-pagelines"></i>  <strong>Light Project Tracking</strong>  </h2>
            
        </div>


    </nav>
</div>