TeamProjectWeb/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TeamProjectWeb.Models
{
    public class ProjectViewModel
    {
        public int ProjectId { get; set; }

        public string ProjectName { get; set; }

        public string ProjectDescription { get; set; }

        //public int? CreatedBy { get; set; }

        public string CreatedByFullName { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime? CreatedDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime? UpdatedDate { get; set; }

        //public bool Status { get; set; }

        public string StatusDescription { get; set; }

        [DisplayFormat(DataFormatString = "{0:##.##%}")]
        public double PercentageCompleted { get; set; }

      
        public virtual IEnumerable<TeamMemberViewModel> TeamMembersViewModel { get; set; }



    }


    public class ProjectItemViewModel
    {
        public int ProjectId { get; set; }

        public string ProjectName { get; set; }

        public string ProjectShortDescription { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime? CreatedDate { get; set; }

      
        public string StatusDescription { get; set; }

        [DisplayFormat(DataFormatString = "{0:##.##%}")]
        public double PercentageCompleted { get; set; }


    }

    
}

TeamProjectWeb/Controllers/MVC/ProjectsController.cs
using TeamProjectWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamProject.Business.Contracts;
using TeamProject.Business.Entities;

namespace TeamProjectWeb.Controllers.MVC
{
    public class ProjectsController : BaseController
    {
        ITeamProjectService _teamProjectService; 
        IContactService _contactService;

        public ProjectsController(ITeamProjectService teamProjectService, IContactService contactService)
        {
            _teamProjectService = teamProjectService;
            _contactService = contactService;
        }

        // GET: Projects
        public ActionResult Index()
        {
            IEnumerable<Project> projects=  _teamProjectService.GetTeamProjects();
            IEnumerable<ProjectItemViewModel> projectItems = new ViewModelFactory().Create(projects);
            return View(projectItems);
        }

        // GET: Projects/Details/5
        public ActionResult Details(int id)
        {
          Project project=  _teamProjectService.GetTeamProject(id);
          ProjectViewModel projectViewModel = new ViewModelFactory(_contactService).Create(project);
          return View(projectViewModel);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Projects/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Projects/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TeamProjectWeb/Controllers/MVC/WorkItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamProject.Business.Contracts;
using TeamProject.Business.Entities;
using TeamProject.Common;
using TeamProjectWeb.Models;
using TeamProjectWeb.Infrastructure;

namespace TeamProjectWeb.Controllers.MVC
{
    public class WorkItemsController : BaseController
    {

        #region properties

        public int ProjectId {
            get 
            {
                return (int)SessionStateHelper.Get(SessionStateKeys.ProjectIdKey);
            }
            set 
            {
                SessionStateHelper.Set(SessionStateKeys.ProjectIdKey, value);
            } 
        }

        public StatusEnum SelectedStatus
        {
            get
            {
                return (StatusEnum)SessionStateHelper.Get(SessionStateKeys.SelectedStatusKey);
            }
            set
            {
                SessionStateHelper.Set(SessionStateKeys.SelectedStatusKey, value);
            }
        }



        public WorkItemsMenuViewModel MenuWorkItemsSession
        {
            get 
            {
                var workitemMenuVM = (WorkItemsMenuViewModel)SessionStateHelper.Get(SessionStateKeys.MenuWorkItemsSessionKey);
                if (workitemMenuVM != null && workitemMenuVM.ProjectId == ProjectId)
                {
                    workitemMenuVM.SelectedFilterStatus = SelectedStatus;
                    return workitemMenuVM;
                }
                else
                {

                    WorkItemsMenuItemsCounterViewModel menu=new  WorkItemsMenuItemsCounterViewModel();

                    menu.ToDoCounter = _workItemsManager.Count(ProjectId, StatusEnum.ToDo);
                    menu.InProgressCounter = _workItemsManager.Count(ProjectId, StatusEnum.InProgress);
                    menu.DoneCounter = _workItemsManager.Count(ProjectId, StatusEnum.Done);
                    menu.OnHoldCounter = _workItemsManager.Count(ProjectId, StatusEnum.OnHold);
                    menu.CancelledCounter = _workItemsManager.Count(ProjectId, StatusEnum.Cancelled);
                    menu.DeletedCounter = _workItemsManager.Count(ProjectId, StatusEnum.Deleted);

                    var workitemMenuViewModel = new WorkItemsMenuViewModel()
                    {
                        ProjectId = ProjectId,
                        ProjectName = ProjectViewModelSession.ProjectName,
                        MenuItemsStatusCounter = menu,
                        SelectedFilterStatus = SelectedStatus
                    };
                    //Store it back to the session variable
                    MenuWorkItemsSession = workitemMenuViewModel;

                    return workitemMenuViewModel;
                }
           }
            set 
            {
                SessionStateHelper.Set(SessionStateKeys.MenuWorkItemsSessionKey,value);
            } 
        }

        public ProjectViewModel ProjectViewModelSession
        {
            get
            {
                if (SessionStateHelper.Get(SessionStateKeys.ProjectViewModelSessionKey) != null)
                {
                    return (ProjectViewModel)SessionStateHelper.Get(SessionStateKeys.ProjectViewModelSessionKey);
                }
                else
                {
                    Project project = _teamProjectService.GetTeamProject(ProjectId);

                    //Store the project in session
                    ProjectViewModel ProjectViewModelSession = TheModelFactory.Create(project);
                    return ProjectViewModelSession;
                }
            }
            set
            {
                SessionStateHelper.Set(SessionStateKeys.ProjectViewModelSessionKey, value);
            }
        }

        #endregion

        private ICommonService _commonManager;
        private IWorkItemsService _workItemsManager;
        private ITeamProjectService _teamProjectService; 

        private ViewModelFactory _theModelFactory;
        protected ViewModelFactory TheModelFactory
        {
            get
            {
                if (_theModelFactory == null)
                {
                    _theModelFactory = new ViewModelFactory(_commonManager);
                }
                return _theModelFactory;
            }
        }

       
        public WorkItemsController(ICommonService commonManager, IWorkItemsService workItemsManager, ITeamProjectService teamProjectService)
        {
            _commonManager = commonManager;
            _workItemsManager = workItemsManager;
            _teamProjectService = teamProjectService;
        }

        // GET: WorkItems
        public ActionResult Index( int id,int status=(int)StatusEnum.ToDo)
        {
            //Get the selected workitem status
            StatusEnum selected=(StatusEnum)id;
            //Set the specific project in the session
            ProjectId = id;
            SelectedStatus = (StatusEnum)status;

            //Get all the workitmes for a specific project
            IEnumerable<WorkItem> workItems = _workItemsManager.Get(ProjectId, (StatusEnum)status);
            IEnumerable<WorkItemViewModel> wItemsVM = TheModelFactory.Create(workItems);

            foreach (var member in wItemsVM)
            {
                member.TeamMember = (TeamMemberViewModel)ProjectViewModelSession.TeamMembersViewModel.Where(s => s.TeamMemberId == member.TeamMemberId).FirstOrDefault();  
            }

            //Get left menu information and set the selected status
            WorkItemsMenuViewModel workItemsMenu = MenuWorkItemsSession;
           
             
            //Create the container that will be sent to the view.
            WorkItemsContainerViewModel wItemContainer = new WorkItemsContainerViewModel()
            {
                WorkItemsViewModelList = wItemsVM,
                WorkItemsMenu = workItemsMenu
            };
           
            return View(wItemContainer);
        }

        // GET: WorkItems/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WorkItems/Create
        public ActionResult Create()
        {
            //Create an empty work item
            WorkItem workItem = new WorkItem()
            {
                ProjectId = ProjectId
            };

            //Set initial values to the view model that will be rendered in the view
            WorkItemViewModel wItem = TheModelFactory.Create(workItem);
            wItem.Mode = Mode.Create;
            wItem.DueDate = DateTime.Now.Date;
            wItem.ProjectName = ProjectViewModelSession.ProjectName;

            //Set the list of team members that will be shown in the drop down for selection
            IEnumerable<TeamMemberViewModel> teamMemberList= ProjectViewModelSession.TeamMembersViewModel;
            wItem.TeamMemberList = new SelectList(teamMemberList, "TeamMemberId", "FullName");

            //Wrap the container
            WorkItemContainerViewModel container = new WorkItemContainerViewModel()
            {
                WorkItemsMenu = MenuWorkItemsSession,
                WorkItemViewModel = wItem
            };
            return View(container);

        }

        // POST: WorkItems/Create
        [HttpPost]
        public ActionResult Create(WorkItemViewModel workItemModel)
        {
            try
            {
                //todo: Validate the model

                WorkItem workItem = TheModelFactory.Parse(workItemModel);
                //Save the information
                WorkItem updatedWorkItem = _workItemsManager.UpdateWorkItem(workItem);
                WorkItemViewModel wItemViewModel = TheModelFactory.Create(updatedWorkItem);

                InvalidateSessions();

                return RedirectToAction("Index", new { id =workItem.ProjectId, status= workItem.Status });
            }
            catch
            {
                return View();
            }
        }

        


        [HttpPost]
        public ActionResult Draft(WorkItemViewModel workItem)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: WorkItems/Edit/5
        public ActionResult Edit(int id)
        {

            //Get information about the specific workItem
            WorkItem workItem = _workItemsManager.GetWorkItem(id);

            WorkItemViewModel wItem= TheModelFactory.Create(workItem);
            wItem.Mode = Mode.Edit;
            wItem.ProjectName = this.ProjectViewModelSession.ProjectName;
          
            IEnumerable<TeamMemberViewModel> teamMemberList = ProjectViewModelSession.TeamMembersViewModel;
            wItem.TeamMemberList = new SelectList(teamMemberList, "TeamMemberId", "FullName");


            WorkItemContainerViewModel container = new WorkItemContainerViewModel()
            {
                WorkItemViewModel=wItem,
                WorkItemsMenu=MenuWorkItemsSession
            };
            
            return View(container);

        }

        // POST: WorkItems/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, WorkItemViewModel workItemModel)
        {
            try
            {
               
                WorkItem workItem = TheModelFactory.Parse(workItemModel);
                WorkItem updatedWorkItem = _workItemsManager.UpdateWorkItem(workItem);
                WorkItemViewModel wItemViewModel = TheModelFactory.Create(updatedWorkItem);

                InvalidateSessions();

                return RedirectToAction("Index", new { id = workItem.ProjectId, status = workItem.Status });

            }
            catch
            {
                return View();
            }
        }

        // GET: WorkItems/Delete/5
        public ActionResult Delete(int id)
        {

TeamProjectWeb/Views/Projects/Details.cshtml
@using TeamProjectWeb.Models

@model ProjectViewModel 

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Project detail</h2>
       <!-- <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Projects")">Projects</a>
            </li>
            <li class="active">
                <strong>Project detail</strong>
            </li>
        </ol>-->
    </div>
</div>
<div class="row">
    <div class="col-lg-9">
        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="m-b-md">
                                @Html.ActionLink("Work Items", "Index", "WorkItems", new { id = Model.ProjectId },new { @class="btn btn-primary btn-xs pull-right"})
                                <!--<a href="#" class="btn btn-white btn-xs pull-right">Edit project</a>-->
                                <h2><b>@Html.DisplayFor(m => m.ProjectName)</b></h2>
                            </div>
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-5">
                            <dl class="dl-horizontal">
                                <dt>Completed:</dt>
                                <dd>@Html.DisplayFor(m => m.PercentageCompleted)</dd>
                                <dt>Status</dt>
                                <dd>
                                    <span class="label label-primary">
                                        @Html.DisplayFor(m => m.StatusDescription)
                                    </span>

                                </dd>
                          
                            </dl>
                        </div>
                        <div class="col-lg-7" id="cluster_info">
                            <dl class="dl-horizontal">

                                <dt>Last Updated:</dt>
                                <dd> @Html.DisplayFor(m => m.UpdatedDate)</dd>
                                <dt>Created:</dt>
                                <dd>@Html.DisplayFor(m=>m.CreatedDate)</dd>
                            
                            </dl>
                        </div>
                    </div>
                  
                    <div class="row m-t-sm">
                        <div class="col-lg-12">
                  
                            <div class="well">
                                    <h3>Description</h3>
                                    <p>@Model.ProjectDescription</p>
                                
                            </div>

                            <div class="panel blank-panel">
                                <div class="panel-heading">
                                    <div class="panel-options">
                                        <ul class="nav nav-tabs">
                                            <li class="active"><a href="#tab-1" data-toggle="tab">Team Members</a></li>
                                       
                                        </ul>
                                    </div>
                                </div>

                                <div class="panel-body">

                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab-1">
                                            <div class="feed-activity-list">
                                                @foreach(var member in Model.TeamMembersViewModel )
                                                {
                                                <div class="feed-element">
                                                    <a href="#" class="pull-left">
                                                        <img alt="image" class="img-circle" src="@Url.Content(member.PhotoPath)">
                                                    </a>
                                                    <div class="media-body ">
                                                       <!-- <small class="pull-right">2h ago</small> -->
                                                        <strong>@member.FullName</strong> - <strong>@member.Role</strong> <br>
                                                        <!--<small class="text-muted">@member.Role</small>-->
                                                        <div class="well">
                                                            @member.Description
                                                        </div>
                                                    </div>
                                                </div>
                                                }


                                 
                                            </div>

                                        </div>
                                      
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="wrapper wrapper-content project-manager">
     
        </div>
    </div>
</div>

TeamProjectWeb/Views/Projects/Index.cshtml
@using TeamProjectWeb.Models
@using TeamProject.Common

@model IEnumerable<ProjectItemViewModel>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Project Management</h2>
    
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">

            <div class="ibox">
                <div class="ibox-title">
                    <h4>Project List</h4>
         
                </div>
                <div class="ibox-content">
                    <div class="row m-b-sm m-t-sm">
                   
                    <div class="project-list">

                        <table class="table table-hover">
                            <tbody>

                                @foreach (var p in Model)
                                { 
                                <tr>
                                    <td class="project-status">
                                        <span class="label label-primary">@Html.DisplayFor(m=>p.StatusDescription)</span>
                                    </td>
                                    <td class="project-title">
                                        <a href="@Url.Action("Details", "Projects", new { id = p.ProjectId })">@p.ProjectName</a><br />
                                       <small>Created @Html.DisplayFor(m => p.CreatedDate)</small>
                                    </td>

                                    <td>
                                        @p.ProjectShortDescription
                                    </td>

                                    <td class="project-completion">
                                        <small>Completion with: @Html.DisplayFor(m=>p.PercentageCompleted) </small>
                                        <div class="progress progress-mini">
                                            <div style="width: @Html.DisplayFor(m=>p.PercentageCompleted)" class="progress-bar"></div>
                                        </div>

                                  
                                       
                        <td class="project-actions">
                                        <a href="@Url.Action("Index", "WorkItems", new { id =(int)p.ProjectId, status= (int)StatusEnum.ToDo})" class="btn btn-white btn-sm"><i class="fa fa-tasks"></i>  Work Items </a>
                                        <a href="@Url.Action("Details", "Projects", new { id = p.ProjectId })" class="btn btn-white btn-sm"><i class="fa fa-folder"></i>  View </a>
                                      
                                    </td>
                                </tr>
                                }
                     
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>